export enum EMassiveStatus {
    CREATED = 'CREADO',
    READY_PROCESS = 'LISTO_PROCESAR',
    PROCESSING =  'PROCESANDO',
    INVALID = 'INVALIDO',
    CANCEL = 'CANCELADO',
    FINALIZED = 'FINALIZADO'
}