export enum ETransactionTypes {
  RE_EMISION = 'REEMISION',
  EMISION = 'EMISION',
  INDIVIDUAL_INCREASE = 'INDIVIDUAL_INCREASE',
  INDIVIDUAL_DECREASE = 'INDIVIDUAL_DECREASE',
  MASSIVE_INCREMENT = 'MASSIVE_INCREMENT',
  MASSIVE_DECREMENT = 'MASSIVE_DECREMENT',
  TRANSFER = 'TRANSFER'
}